package main

var settings_apk_debug string = `package: name='io.appium.settings' versionCode='101' versionName='5.12.11' platformBuildVersionName='12' platformBuildVersionCode='32' compileSdkVersion='32' compileSdkVersionCodename='12'
sdkVersion:'21'
targetSdkVersion:'32'
uses-permission: name='android.permission.DISABLE_KEYGUARD'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.CHANGE_NETWORK_STATE'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.READ_PHONE_STATE'
uses-permission: name='android.permission.WRITE_SETTINGS'
uses-permission: name='android.permission.CHANGE_WIFI_STATE'
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
uses-permission: name='android.permission.ACCESS_BACKGROUND_LOCATION'
uses-permission: name='android.permission.ACCESS_MOCK_LOCATION'
uses-permission: name='android.permission.SET_ANIMATION_SCALE'
uses-permission: name='android.permission.CHANGE_CONFIGURATION'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='android.permission.BLUETOOTH'
uses-permission: name='android.permission.BLUETOOTH_ADMIN'
uses-permission: name='android.permission.READ_SMS'
uses-permission: name='android.permission.RECORD_AUDIO'
application-label:'Appium Settings'
application-label-af:'Appium Settings'
application-label-am:'Appium Settings'
application-label-ar:'Appium Settings'
application-label-as:'Appium Settings'
application-label-az:'Appium Settings'
application-label-be:'Appium Settings'
application-label-bg:'Appium Settings'
application-label-bn:'Appium Settings'
application-label-bs:'Appium Settings'
application-label-ca:'Appium Settings'
application-label-cs:'Appium Settings'
application-label-da:'Appium Settings'
application-label-de:'Appium Settings'
application-label-el:'Appium Settings'
application-label-en-AU:'Appium Settings'
application-label-en-CA:'Appium Settings'
application-label-en-GB:'Appium Settings'
application-label-en-IN:'Appium Settings'
application-label-en-XC:'Appium Settings'
application-label-es:'Appium Settings'
application-label-es-US:'Appium Settings'
application-label-et:'Appium Settings'
application-label-eu:'Appium Settings'
application-label-fa:'Appium Settings'
application-label-fi:'Appium Settings'
application-label-fr:'Appium Settings'
application-label-fr-CA:'Appium Settings'
application-label-gl:'Appium Settings'
application-label-gu:'Appium Settings'
application-label-hi:'Appium Settings'
application-label-hr:'Appium Settings'
application-label-hu:'Appium Settings'
application-label-hy:'Appium Settings'
application-label-in:'Appium Settings'
application-label-is:'Appium Settings'
application-label-it:'Appium Settings'
application-label-iw:'Appium Settings'
application-label-ja:'Appium Settings'
application-label-ka:'Appium Settings'
application-label-kk:'Appium Settings'
application-label-km:'Appium Settings'
application-label-kn:'Appium Settings'
application-label-ko:'Appium Settings'
application-label-ky:'Appium Settings'
application-label-lo:'Appium Settings'
application-label-lt:'Appium Settings'
application-label-lv:'Appium Settings'
application-label-mk:'Appium Settings'
application-label-ml:'Appium Settings'
application-label-mn:'Appium Settings'
application-label-mr:'Appium Settings'
application-label-ms:'Appium Settings'
application-label-my:'Appium Settings'
application-label-nb:'Appium Settings'
application-label-ne:'Appium Settings'
application-label-nl:'Appium Settings'
application-label-or:'Appium Settings'
application-label-pa:'Appium Settings'
application-label-pl:'Appium Settings'
application-label-pt:'Appium Settings'
application-label-pt-BR:'Appium Settings'
application-label-pt-PT:'Appium Settings'
application-label-ro:'Appium Settings'
application-label-ru:'Appium Settings'
application-label-si:'Appium Settings'
application-label-sk:'Appium Settings'
application-label-sl:'Appium Settings'
application-label-sq:'Appium Settings'
application-label-sr:'Appium Settings'
application-label-sr-Latn:'Appium Settings'
application-label-sv:'Appium Settings'
application-label-sw:'Appium Settings'
application-label-ta:'Appium Settings'
application-label-te:'Appium Settings'
application-label-th:'Appium Settings'
application-label-tl:'Appium Settings'
application-label-tr:'Appium Settings'
application-label-uk:'Appium Settings'
application-label-ur:'Appium Settings'
application-label-uz:'Appium Settings'
application-label-vi:'Appium Settings'
application-label-zh-CN:'Appium Settings'
application-label-zh-HK:'Appium Settings'
application-label-zh-TW:'Appium Settings'
application-label-zu:'Appium Settings'
application-icon-120:'res/drawable-ldpi-v4/ic_launcher.png'
application-icon-160:'res/drawable-mdpi-v4/ic_launcher.png'
application-icon-240:'res/drawable-hdpi-v4/ic_launcher.png'
application-icon-320:'res/drawable-xhdpi-v4/ic_launcher.png'
application-icon-480:'res/drawable-xxhdpi-v4/ic_launcher.png'
application-icon-640:'res/drawable-xxxhdpi-v4/ic_launcher.png'
application: label='Appium Settings' icon='res/drawable-mdpi-v4/ic_launcher.png'
application-debuggable
launchable-activity: name='io.appium.settings.Settings'  label='' icon=''
feature-group: label=''
  uses-feature: name='android.hardware.wifi'
  uses-feature: name='android.hardware.bluetooth'
  uses-implied-feature: name='android.hardware.bluetooth' reason='requested android.permission.BLUETOOTH permission, requested android.permission.BLUETOOTH_ADMIN permission, and targetSdkVersion > 4'
  uses-feature: name='android.hardware.faketouch'
  uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
  uses-feature: name='android.hardware.location'
  uses-implied-feature: name='android.hardware.location' reason='requested android.permission.ACCESS_COARSE_LOCATION permission, requested android.permission.ACCESS_FINE_LOCATION permission, and requested android.permission.ACCESS_MOCK_LOCATION permission'
  uses-feature: name='android.hardware.microphone'
  uses-implied-feature: name='android.hardware.microphone' reason='requested android.permission.RECORD_AUDIO permission'
  uses-feature: name='android.hardware.telephony'
  uses-implied-feature: name='android.hardware.telephony' reason='requested a telephony permission'
provides-component:'ime'
provides-component:'notification-listener'
main
other-activities
other-receivers
other-services
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--' 'af' 'am' 'ar' 'as' 'az' 'be' 'bg' 'bn' 'bs' 'ca' 'cs' 'da' 'de' 'el' 'en-AU' 'en-CA' 'en-GB' 'en-IN' 'en-XC' 'es' 'es-US' 'et' 'eu' 'fa' 'fi' 'fr' 'fr-CA' 'gl' 'gu' 'hi' 'hr' 'hu' 'hy' 'in' 'is' 'it' 'iw' 'ja' 'ka' 'kk' 'km' 'kn' 'ko' 'ky' 'lo' 'lt' 'lv' 'mk' 'ml' 'mn' 'mr' 'ms' 'my' 'nb' 'ne' 'nl' 'or' 'pa' 'pl' 'pt' 'pt-BR' 'pt-PT' 'ro' 'ru' 'si' 'sk' 'sl' 'sq' 'sr' 'sr-Latn' 'sv' 'sw' 'ta' 'te' 'th' 'tl' 'tr' 'uk' 'ur' 'uz' 'vi' 'zh-CN' 'zh-HK' 'zh-TW' 'zu'
densities: '120' '160' '240' '320' '480' '640'`

var qr_code_gen string = `package: name='com.ring.aqa.qrcodegen' versionCode='1' versionName='1.0' platformBuildVersionName='10' platformBuildVersionCode='29' compileSdkVersion='29' compileSdkVersionCodename='10'
sdkVersion:'26'
targetSdkVersion:'29'
application-label:'QR-Code Gen'
application-label-af:'QR-Code Gen'
application-label-am:'QR-Code Gen'
application-label-ar:'QR-Code Gen'
application-label-as:'QR-Code Gen'
application-label-az:'QR-Code Gen'
application-label-be:'QR-Code Gen'
application-label-bg:'QR-Code Gen'
application-label-bn:'QR-Code Gen'
application-label-bs:'QR-Code Gen'
application-label-ca:'QR-Code Gen'
application-label-cs:'QR-Code Gen'
application-label-da:'QR-Code Gen'
application-label-de:'QR-Code Gen'
application-label-el:'QR-Code Gen'
application-label-en-AU:'QR-Code Gen'
application-label-en-CA:'QR-Code Gen'
application-label-en-GB:'QR-Code Gen'
application-label-en-IN:'QR-Code Gen'
application-label-en-XC:'QR-Code Gen'
application-label-es:'QR-Code Gen'
application-label-es-US:'QR-Code Gen'
application-label-et:'QR-Code Gen'
application-label-eu:'QR-Code Gen'
application-label-fa:'QR-Code Gen'
application-label-fi:'QR-Code Gen'
application-label-fr:'QR-Code Gen'
application-label-fr-CA:'QR-Code Gen'
application-label-gl:'QR-Code Gen'
application-label-gu:'QR-Code Gen'
application-label-hi:'QR-Code Gen'
application-label-hr:'QR-Code Gen'
application-label-hu:'QR-Code Gen'
application-label-hy:'QR-Code Gen'
application-label-in:'QR-Code Gen'
application-label-is:'QR-Code Gen'
application-label-it:'QR-Code Gen'
application-label-iw:'QR-Code Gen'
application-label-ja:'QR-Code Gen'
application-label-ka:'QR-Code Gen'
application-label-kk:'QR-Code Gen'
application-label-km:'QR-Code Gen'
application-label-kn:'QR-Code Gen'
application-label-ko:'QR-Code Gen'
application-label-ky:'QR-Code Gen'
application-label-lo:'QR-Code Gen'
application-label-lt:'QR-Code Gen'
application-label-lv:'QR-Code Gen'
application-label-mk:'QR-Code Gen'
application-label-ml:'QR-Code Gen'
application-label-mn:'QR-Code Gen'
application-label-mr:'QR-Code Gen'
application-label-ms:'QR-Code Gen'
application-label-my:'QR-Code Gen'
application-label-nb:'QR-Code Gen'
application-label-ne:'QR-Code Gen'
application-label-nl:'QR-Code Gen'
application-label-or:'QR-Code Gen'
application-label-pa:'QR-Code Gen'
application-label-pl:'QR-Code Gen'
application-label-pt:'QR-Code Gen'
application-label-pt-BR:'QR-Code Gen'
application-label-pt-PT:'QR-Code Gen'
application-label-ro:'QR-Code Gen'
application-label-ru:'QR-Code Gen'
application-label-si:'QR-Code Gen'
application-label-sk:'QR-Code Gen'
application-label-sl:'QR-Code Gen'
application-label-sq:'QR-Code Gen'
application-label-sr:'QR-Code Gen'
application-label-sr-Latn:'QR-Code Gen'
application-label-sv:'QR-Code Gen'
application-label-sw:'QR-Code Gen'
application-label-ta:'QR-Code Gen'
application-label-te:'QR-Code Gen'
application-label-th:'QR-Code Gen'
application-label-tl:'QR-Code Gen'
application-label-tr:'QR-Code Gen'
application-label-uk:'QR-Code Gen'
application-label-ur:'QR-Code Gen'
application-label-uz:'QR-Code Gen'
application-label-vi:'QR-Code Gen'
application-label-zh-CN:'QR-Code Gen'
application-label-zh-HK:'QR-Code Gen'
application-label-zh-TW:'QR-Code Gen'
application-label-zu:'QR-Code Gen'
application-icon-160:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-240:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-320:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-480:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-640:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-65534:'res/mipmap-anydpi-v26/ic_launcher.xml'
application: label='QR-Code Gen' icon='res/mipmap-anydpi-v26/ic_launcher.xml'
launchable-activity: name='com.ring.aqa.qrcodegen.MainActivity'  label='' icon=''
feature-group: label=''
  uses-feature: name='android.hardware.faketouch'
  uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
main
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--' 'af' 'am' 'ar' 'as' 'az' 'be' 'bg' 'bn' 'bs' 'ca' 'cs' 'da' 'de' 'el' 'en-AU' 'en-CA' 'en-GB' 'en-IN' 'en-XC' 'es' 'es-US' 'et' 'eu' 'fa' 'fi' 'fr' 'fr-CA' 'gl' 'gu' 'hi' 'hr' 'hu' 'hy' 'in' 'is' 'it' 'iw' 'ja' 'ka' 'kk' 'km' 'kn' 'ko' 'ky' 'lo' 'lt' 'lv' 'mk' 'ml' 'mn' 'mr' 'ms' 'my' 'nb' 'ne' 'nl' 'or' 'pa' 'pl' 'pt' 'pt-BR' 'pt-PT' 'ro' 'ru' 'si' 'sk' 'sl' 'sq' 'sr' 'sr-Latn' 'sv' 'sw' 'ta' 'te' 'th' 'tl' 'tr' 'uk' 'ur' 'uz' 'vi' 'zh-CN' 'zh-HK' 'zh-TW' 'zu'
densities: '160' '240' '320' '480' '640' '65534'`

var appium_uiautomator2_server_v string = `package: name='io.appium.uiautomator2.server' versionCode='184' versionName='7.0.22' platformBuildVersionName='14' platformBuildVersionCode='34' compileSdkVersion='34' compileSdkVersionCodename='14'
sdkVersion:'21'
targetSdkVersion:'34'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.CHANGE_WIFI_STATE'
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.BLUETOOTH_SCAN'
uses-permission: name='android.permission.BLUETOOTH' maxSdkVersion='30'
uses-permission: name='android.permission.QUERY_ALL_PACKAGES'
uses-permission: name='android.permission.REORDER_TASKS'
application: label='' icon=''
application-debuggable
feature-group: label=''
  uses-feature: name='android.hardware.bluetooth'
  uses-implied-feature: name='android.hardware.bluetooth' reason='requested android.permission.BLUETOOTH permission, and targetSdkVersion > 4'
  uses-feature: name='android.hardware.faketouch'
  uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
  uses-feature: name='android.hardware.wifi'
  uses-implied-feature: name='android.hardware.wifi' reason='requested android.permission.ACCESS_WIFI_STATE permission, and requested android.permission.CHANGE_WIFI_STATE permission'
other-activities
other-receivers
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '160'`

var appium_uiautomator2_server_debug_androidTest string = `package: name='io.appium.uiautomator2.server.test' versionCode='' versionName='' platformBuildVersionName='14' platformBuildVersionCode='34' compileSdkVersion='34' compileSdkVersionCodename='14'
sdkVersion:'21'
targetSdkVersion:'34'
application: label='' icon=''
application-debuggable
uses-library:'android.test.runner'
feature-group: label=''
  uses-feature: name='android.hardware.faketouch'
  uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '160'`

var ring_develop string = `package: name='com.ringapp.debug' versionCode='1' versionName='3.82.0_5f7b591_develop_google' platformBuildVersionName='15' platformBuildVersionCode='35' compileSdkVersion='35' compileSdkVersionCodename='15'
minSdkVersion:'28'
targetSdkVersion:'35'
uses-permission: name='android.permission.FOREGROUND_SERVICE'
uses-permission: name='android.permission.FOREGROUND_SERVICE_DATA_SYNC'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
uses-permission: name='android.permission.VIBRATE'
uses-permission: name='android.permission.BLUETOOTH' maxSdkVersion='30'
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.BLUETOOTH_SCAN' usesPermissionFlags='neverForLocation'
uses-permission: name='android.permission.BLUETOOTH_CONNECT'
uses-permission: name='android.permission.BLUETOOTH_ADMIN' maxSdkVersion='30'
uses-permission: name='android.permission.RECEIVE_BOOT_COMPLETED'
uses-permission: name='android.permission.CAMERA'
uses-permission: name='android.permission.USE_FULL_SCREEN_INTENT'
uses-permission: name='android.permission.NFC'
uses-permission: name='android.permission.ACCESS_WIFI_STATE'
uses-permission: name='android.permission.FOREGROUND_SERVICE_LOCATION'
uses-permission: name='android.permission.FOREGROUND_SERVICE_CONNECTED_DEVICE'
uses-permission: name='android.permission.ACCESS_BACKGROUND_LOCATION'
uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
uses-permission: name='android.permission.CHANGE_NETWORK_STATE'
uses-permission: name='android.permission.WRITE_CONTACTS'
uses-permission: name='android.permission.READ_CONTACTS'
uses-permission: name='android.permission.RECORD_AUDIO'
uses-permission: name='android.permission.WAKE_LOCK'
uses-permission: name='android.permission.BLUETOOTH_PRIVILEGED'
uses-permission: name='android.permission.BROADCAST_STICKY'
uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
uses-permission: name='com.ringapp.permission.C2D_MESSAGE'
uses-permission: name='android.permission.CHANGE_WIFI_STATE'
uses-permission: name='android.permission.DOWNLOAD_WITHOUT_NOTIFICATION'
uses-permission: name='android.permission.POST_NOTIFICATIONS'
uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
uses-permission: name='android.permission.MODIFY_AUDIO_SETTINGS'
uses-permission: name='android.permission.READ_PHONE_STATE'
application-label:'Ring Beta'
application-icon-160:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-240:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-320:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-480:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-640:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-65534:'res/mipmap-anydpi-v26/ic_launcher.xml'
application-icon-65535:'res/mipmap-anydpi-v26/ic_launcher.xml'
application: label='Ring Beta' icon='res/mipmap-anydpi-v26/ic_launcher.xml'
application-debuggable
launchable-activity: name='com.ring.launch.LaunchActivity'  label='' icon=''
uses-library-not-required:'org.apache.http.legacy'
uses-library-not-required:'androidx.window.extensions'
uses-library-not-required:'androidx.window.sidecar'
feature-group: label=''
  uses-gl-es: '0x20000'
  uses-feature-not-required: name='android.hardware.bluetooth'
  uses-feature: name='android.hardware.bluetooth_le'
  uses-feature-not-required: name='android.hardware.camera'
  uses-feature-not-required: name='android.hardware.location.gps'
  uses-feature-not-required: name='android.hardware.wifi'
  uses-feature: name='android.hardware.faketouch'
  uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
  uses-feature: name='android.hardware.location'
  uses-implied-feature: name='android.hardware.location' reason='requested android.permission.ACCESS_COARSE_LOCATION permission, and requested android.permission.ACCESS_FINE_LOCATION permission'
  uses-feature: name='android.hardware.microphone'
  uses-implied-feature: name='android.hardware.microphone' reason='requested android.permission.RECORD_AUDIO permission'
  uses-feature: name='android.hardware.screen.landscape'
  uses-implied-feature: name='android.hardware.screen.landscape' reason='one or more activities have specified a landscape orientation'
  uses-feature: name='android.hardware.screen.portrait'
  uses-implied-feature: name='android.hardware.screen.portrait' reason='one or more activities have specified a portrait orientation'
provides-component:'app-widget'
main
other-activities
other-receivers
other-services
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--'
densities: '160' '240' '320' '480' '640' '65534' '65535'
native-code: 'arm64-v8a' 'armeabi-v7a' 'x86'
`
